version: '3'
services:
  db:
    image: mongo:latest
    env_file:
      - ./db/db.env
    ports:
      - "27017:27017"
  ips:
    build: ./ips/
    ports:
      - "80:8080"
    env_file:
      - ./ips/ips.env