version: '3'
services:
  db:
    build: ./db/
    env_file:
      - ./db/db.env
    expose:
      - "27017"
  web:
    build: ./ips/
    ports:
      - "4000:80"
    env_file:
      - ./ips/ips.env
    command: sh -c './wait-for.sh db:27017 -t 10 -- $GOPATH/src/rhodopsin-micros/ips/ips'
    depends_on:
      - db